### ISSUE TITLE
Error message when ran the updated get_alleles.py

### ISSUE THREAD

**Issue by Arturiali** [tomdstanton/GetAlleles#5]
Hi,
When I ran the updated get_alleles.py to process a genome file, I encountered the following error message and the output file contains no content.

**Error prompted in the terminal**
```python
Traceback (most recent call last):
  File "/fs03/kr58/jiahui/OmpK_type/getallelets/get_alleles.py", line 444, in <module>
    main()
  File "/fs03/kr58/jiahui/OmpK_type/getallelets/get_alleles.py", line 415, in main
    orthologs = list(get_alleles(
  File "/fs03/kr58/jiahui/OmpK_type/getallelets/get_alleles.py", line 357, in get_alleles
    for orf in extract_orfs(assembly, ref, verbose=verbose, **kwargs):
  File "/fs03/kr58/jiahui/OmpK_type/getallelets/get_alleles.py", line 343, in extract_orfs
    assembly.seq(a.ctg, new_ref_start, new_ref_end, a.strand))
  File "/fs03/kr58/jiahui/OmpK_type/getallelets/get_alleles.py", line 129, in seq
    return self.aligner.seq(ctg, start, end) if strand == 1 else mp.revcomp(self.aligner.seq(ctg, start, end))
  File "python/mappy.pyx", line 268, in mappy.revcomp
TypeError: object of type 'NoneType' has no len()
```
The following are the command line and the reference sequence file, as well as the inquiry files used.

**Command line code used**
```shell
python get_alleles.py /fs03/kr58/jiahui/OmpK_type/getallelets/ffn/ARE29922.1_OmpK35_gene_references.ffn /fs03/kr58/jiahui/assemblies_all_1300/KPEH351.fasta --all ompk35 -i 80 -c 60 -p > ompk35_alleles_KPEH351.tsv
``` 
**Reference genome**
[ARE29922.1_OmpK35_gene_references.ffn.txt](https://github.com/user-attachments/files/15756034/ARE29922.1_OmpK35_gene_references.ffn.txt)

**Inquiry genome**
[KPEH351.fasta.txt](https://github.com/user-attachments/files/15756038/KPEH351.fasta.txt)

**Comment by tomdstanton** [comment]
Fixed in v0.0.2
